language: python
python:
- '3.8'
services:
- postgresql
addons:
  postgresql: '9.6'
install:
- pip install -r requirements.txt
before_script:
- psql --version
- psql -c 'create database roadtrip_test;' -U postgres
- python manage.py db upgrade
script:
- pytest
deploy:
  provider: heroku
  api_key:
    secure: LfAbZpdDiO4hBBP6KmbOkW+Wj4Heyn16m38ZufLrl9ftxol6pyj8yWyDgV+ZmcqppDwhFTpxZIEaioI4XYIyJ02PKbPkrQsSvh4Vn54IcZpeAerdb4adcOGaLWIOyD+LgDedSb0QL3W/VIgG4He+LZBH73qMb7p7FFdCpACTOB6o3LOwe8a7CtyzXpNu4LtY+TJtPS1wpq8C2aQOiFs2xrZt4IBgbjV9Hot4fkaAL/0yZjd6R5sy+W4h7lVe78OWr8YbqF9LoWrLwypm08CfQyhd7t3+JzC3VB/KZt/Ibm+v5SKs7cdk21v08BfJisM5fUe3Elkg0AQwZ4iH4Wwp67GlAH3b2OEQY1dzPx4lNC6iR1saQYud0OnWeAxvE1BOSadVaZv2FbK3sVxOggXivrre6uz2DMpapyPb6m+sN/W7elkyR02QGynF2XeyPrHmbgEI0kWHZyZNu1M/f7OHZvtexcg+1sXf3QXG7fGej51KyDNOt8mqmEC0WvNJYBvMq18NFycyRsl4VJb5nZlbUxZc4rzFuGzNzoUm+rY8+HAC06xLiv+2WoTvvBC0vU7gM9IejwDn4zRm87jcRj6QX2lpcyZl8mGxPPCYF5SDBrjcAroykN3GFiCNvjiZNlVtHDRW0WAukvdw+9uHPBZjrdT13sIJdbNefsPp5yqpB34=
  app: iandouglas-ufsnd-capstone
  on:
    repo: iandouglas/udacity-fsnd-capstone
    branch: main
  skip_cleanup: 'true'
  run:
    - pip install -r requirements.txt
    - python manage.py db upgrade
