language: python
python:
- '3.8'
services:
- postgresql
addons:
  postgresql: '9.6'
install:
- pip install -r requirements.txt
before_script:
- psql --version
- psql -c 'create database roadtrip_test;' -U postgres
- python manage.py db upgrade
script:
- pytest
deploy:
  provider: heroku
  api_key:
    secure: YQg2UhPbkgjJwVkxkMPj5rjkpga21cRWXtkgjh4ajg7m8qLIZyW8yk87bLM8ETNZ4LK2sfgpmKA6VIdjK8isEwcMEo7LuyIwNLKaXVBye/kAMDAWqOR+8wBmyIDyzGkpRcvQixaHcZEEnWyus63M15kE0YRGJpb89OSvYr8ECtxf++y5m7bdV3DvTy2xP8RuYZnu+urJyDSQTlQhHQbaW36NwLB50mytRBbyD1SY4r06481ARdHEumjgcH7wltiVpKAdH38q/DFd7MUwqD0Rt8uqNSObwIvVfc12DlQ44PJ30tGiU5oODufuwG3SGfulS6rOfK86vhFBhZrFN7at9CbXQqk7PleS1rSjPF2c2RtrtaWCWH29AiCSlKXczDNq8bIb9yD3R5wNH3JgW5piRJXbUTPyMKn5WEUGBfrEKf+E9tQq+h2v6oA5vl4WIr/rUoMN3cwLUCJXBieXc1PViVZaoUXjG2va1usozFnaM/Q2cDSXZZIVciToTVeiYfYrMJJn5vfvMgjOGRBn85XG8gYF0BJmymWlpjsrhBZzxbBxeFkKRB0iwm/GSXsfd8xzDJen2/prfbC+HSc5SmD1h7THe3XFutYQk+W/aQA32iw00KIfbO4KaMdiv0MVfTyO+nU7Y6AExFue/xA+pLQTwQQvJGKuGG91KmfhE5mviEQ=
  app: iandouglas-ufsnd-capstone
  on:
    repo: iandouglas/udacity-fsnd-capstone
    branch: main
  skip_cleanup: 'true'
