name: PR Project Assigner
on:
  issues:
    types: [opened, reopened]
  pull_request:
    types: [opened, reopened]

jobs:
  build:
    name: Add to project
    runs-on: ubuntu-latest
    steps:
      - uses: ookami-kb/gh-pr-project@v1
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          projectId: MDEwOlJlcG9zaXRvcnkyOTg3Nzg2ODQ=
